version: '3'
services:
  php:
    build: ./docker/php
    volumes:
      - ./:/root/app
    links:
      - mysql
      - pgsql
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test-1
      - PHP_IDE_CONFIG="serverName=Docker"
  pgsql:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test-2
volumes:
  mysql-data:
    external: false
  pgsql-data:
    external: false