version: '3'
services:
  php:
    build: ./docker/php
    volumes:
      - ./:/root/app
    links:
      - mysql
      - pgsql
    networks:
      - net
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DB: test
    networks:
      - net
  pgsql:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./docker/pgsql:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: root
    networks:
      - net
networks:
  net: