#!/usr/bin/env php

<?php
/**
 * Date: 11.04.2020
 * Time: 13:21
 * Author: Artem Aleksandrov
 */

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require_once __DIR__ . '/../../autoload.php';
} else {
    require_once __DIR__ . '/vendor/autoload.php';
}

use kradwhite\migration\command\ConfigCommand;
use kradwhite\migration\command\CreateCommand;
use kradwhite\migration\command\MigrateCommand;
use kradwhite\migration\command\RollbackCommand;
use kradwhite\migration\command\TableCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->addCommands([
    new ConfigCommand(),
    new TableCommand(),
    new CreateCommand(),
    new MigrateCommand(),
    new RollbackCommand(),
]);

$application->run();