paths:
  migrations: "migrations/"

defaults:
  table: migrations
  environment: testing

environments:
  testing:
    driver: pgsql
    host: localhost
    db: test
    user: admin
    pass: admin
    port: 5432
    charset: utf8
    # table: migrations
  production:
    driver: pgsql
    host: localhost
    db: prod
    user: admin
    pass: admin
    port: 5432
    charset: utf8
    # table: migrations