paths:
  migrations: "migrations/"

defaults:
  migration_table: migrations
  environment: testing

environments:
  testing:
    driver: pgsql
    host: localhost
    name: test
    user: admin
    pass: 'admin'
    port: 5432
    charset: utf8
  production:
    driver: pgsql
    host: localhost
    name: prod
    user: admin
    pass: 'admin'
    port: 5432
    charset: utf8
