# %s
paths:

  # %s
  migrations: "migrations/"

# %s
defaults:

  # %s
  table: migrations

  # %s
  environment: testing

# %s
environments:

  # %s
  testing:

    # %s
    driver: pgsql

    # %s
    host: localhost

    # %s
    dbName: test

    # %s
    user: admin

    # %s
    password: admin

    # %s
    port: 5432

    # %s
    charset: utf8

    # %s
    # table: migrations

  production:
    driver: pgsql
    host: localhost
    dbName: prod
    user: admin
    password: admin
    port: 5432
    charset: utf8
    # table: migrations